### PR TITLE
Maintenance Updates

### PR DESCRIPTION
**Pull request by clarkio**
An open PR to prepare for an updated release of the extension. However we lost access to publish to the VS Code marketplace at the moment.

### CODE REVIEW

**Review by MichaelJolley — CHANGES_REQUESTED** [review]
Sorry, but we're going to need more descriptive commit messages or some type of description given in the PR. Don't be trying to submit poor PR's for hacktoberfest. 😄

**Comment by clarkio** [comment]
LOL you trolling me on every platform now @MichaelJolley ?!

In any case, I'll have you know that this is not for hacktoberfest and is intended to bundle changes into a new release. However it looks like I lost access to publish the extension when I left msft 😬😅

**Comment by clarkio** [comment]
Closing this PR as it will no longer be necessary

**Comment by clarkio** [comment]
We'll publish changes separately for each version bump instead of as one whole update

**Pull request closed without merging**
