### PR TITLE
Migrate testing from vscode to @vscode/test-electron

### LINKED ISSUE #148: Migrate from vscode dependency to @vscode/test-electron
[Docs](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode)

[@vscode/test-electron](https://github.com/microsoft/vscode-test)

### PR DESCRIPTION
**Pull request by Technickel-Dev**
Since the recommended way to test vscode extensions has switched from the vscode dependency to @vscode/test-electron, this push makes the changes required to support the new testing setup! This will close #148.

image

The changes are mainly around file tree structure, new test runner and new test script with the required dependencies.
Side note: package-lock.json did some required version updating which is why there are a larger number of changes than expected

I'm doing this as part of Hacktoberfest and a personal interest in such a cool extension. I do not however have very much experience with vscode extensions so feel free to point out any feedback if you see something!

### CODE REVIEW

**Comment by clarkio** [comment]
Thank you for this contribution @Technickel-Dev. Also great timing as I've decided to bring some focus back onto this project recently 🙂👍

**Comment by clarkio** [comment]
This looks to be working overall but for some reason I'm seeing the tests run twice. Have you seen this on your end at all? I notice in your screenshot that they're only run once resulting in 5 tests passing but it shows as 10 for me.
image

**Comment by clarkio** [comment]
Never mind me as I figured it out. I had to clean up my `/out` folder and do a fresh compile since I had the old tests in there as well

**Review by clarkio — APPROVED** [review]
Reviewed all the changes and tested thing locally. All worked as expected and completed tests successfully. Thanks again for making this contribution!

**Comment by Technickel-Dev** [comment]
Glad to help and happy you got it running! If you'll have it, I would love to make some more maintenance-esque PRs. Let me know if there's anything that would be top of your list, otherwise I'll just work on what I see fit.

Also just gotta say, checked out your latest Twitch stream after the fact last night and your intro absolutely made my night. Keep on doing your thing!

**Comment by clarkio** [comment]
@Technickel-Dev that's awesome to hear and thanks for sharing. Glad the stream had a positive impact on you!

And yes definitely open to more contributions but I've just realized I lost access to publish this extension to the VS Code marketplace. I'm in a holding pattern to see if someone from msft can help recover ownership from my deleted employee account.

Don't let that stop you from making contributions where you see opportunities though 🙂👍

**Comment by clarkio** [comment]
Ok so looks like it's gonna be a bit before I can get the test & build workflow related checks working again. With that in mind I'm going to go ahead and merge this as I tested it all locally and it works fine.

Thanks again for this contribution @Technickel-Dev. Also thanks for stopping by the stream again!

**Comment by clarkio** [comment]
@Technickel-Dev did you get credit for this one for Hacktoberfest yet? Let me know if there are any issues with that and if there's something missing from my end to enable you to receive credit.

**Comment by Technickel-Dev** [comment]
No worries on timing you do your thing and glad I could stop by! As for credit, it actually just passed the 7 day hold today, so all is good there and nothing needed on your end! Puts me at 3/4 done or on hold :D

**Comment by clarkio** [comment]
@all-contributors please add @Technickel-Dev for code

**Comment by clarkio** [comment]
@all-contributors please add @Technickel-Dev for test

**Pull request merged**
